apiVersion: v1
kind: Pod
metadata:
  name: sample-serviceaccount-pod
spec:
  serviceAccount: sample-serviceaccount-noautomount
  automountServiceAccountToken: true
  containers:
  - name: nginx-container
    image: nginx:1.15
