apiVersion: v1
kind: Pod
metadata:
  name: sample-privileged
spec:
  containers:
    - name: nginx-container
      image: nginx:1.15
      ports:
      - containerPort: 80
      securityContext:
      # 特権コンテナの作成
        privileged: true
