apiVersion: v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 3
  selector:
    matcbLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
  spec:
    containers:
      - name: nginx-container
        image: nginx:1.15
        ports:
          - containerPort: 80
