apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample-rs-pod
  labels:
    # labelが一致したものがありreplica setよりも多くなった場合podが削除される
    app: sample-app
spec:
  containers:
    - name: nginx-container
      image: nginx:1.15
      ports:
        - containerPort: 80

