apiVersion: v1
kind: Pod
metadata:
  name: sample-env-fail2
  labels:
    app: sample-app
spec:
  containers:
    - name: nginx-container
      image: nginx:1.15
      # commandとargで参照可能なのはpod manifest内で定義された環境変数のみ
      command: ["echo"]
      args: ["$(TESTENV)", "$(HOSTNAME)"]
      env:
        - name: TESTENV
          value: "100"
