apiVersion: v1
kind: Pod
metadata:
  name: sample-env
  labels:
    name: sample-app
spec:
  containers:
  - name: nginx-containar
    image: nginx:1.15
    env:
      - name: MAX_CONNECTION
        value: "100"
      - name:  TZ
        value: Asia/Tokyo
    ports:
      - containerPort: 80
