apiVersion: v1
kind: Pod
metadata:
  name: sample-env-container
  labels:
    name: sample-app
spec:
  containers:
  - name: nginx-container
    image: nginx:1.15
    env:
      - name: CPU_REQUESTS
        valueFrom:
            requestFieldRef:
              containerNmae: nginx-container
              resource: requests.cpu
      - name: CPU_LIMITS
        valueFrom:
            requestFieldRef:
              containerNmae: nginx-container
              resource: limits.cpu
    ports:
      - containerPort: 80
