apiVersion: v1
kind: Pod
metadata:
  name: sample-env-container
  labels:
    name: sample-app
spec:
  containers:
  - name: nginx-container
    image: nginx:1.15
    env:
      - name: CPU_REQUESTS
        valueFrom:
          resourceFieldRef:
            resource: requests.cpu
            containerName: nginx-container
      - name: CPU_LIMITS
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
            containerName: nginx-container
    ports:
      - containerPort: 80
