apiVersion: v1
kind: Pod
metadata:
  name: sample-secret-single-volume
spec:
  containers:
    - name: secret-container
      image: nginx:1.16
      volumeMounts:
        - mountPath: /config
          name: config-volume
  volumes:
    - name: config-volume
      secret:
        secretName: sample-db-auth
