apiVersion: v1
kind: Pod
metadata:
  name: sample-configmap-multi-volume
spec:
  containers:
    - name: configmap-container
      image: nginx:1.16
      volumeMounts:
        - mountPath: /config
          name: config-volume
  volumes:
    - name: config-volume
      configMap:
        name: sample-configmap
